### ISSUE TITLE
Failed to download climatological models

### ISSUE THREAD

**Issue by vlbBTH** [timduly4/pyglow#66]
Hi,

I have been trying to install pyglow but there is an issue on "_make all_" or "_make -C src/pyglow/models source_". More specifically, something seems to go wrong when downloading igrf11. I had a look on the file get_models.py and the url for igrfs11 is "http://www.ngdc.noaa.gov/IAGA/vmod/igrf11.f" which is out (due to the partial government shutdown?). Is there some alternative for this url and any other under the same domain?

BR,
Vinícius Ludwig Barbosa

**Comment by timduly4** [comment]
@vlbBTH This is definitely due to the US government shutdown.  It is difficult for the `pyglow` project to waver between maintainer of the underlying geophysical models and a simple wrapper for them.  (We didn't write IGRF, right?) . The easiest solution is to put a backup in https://github.com/timduly4/pyglow/tree/master/static once the file is available.

**Comment by timduly4** [comment]
@vlbBTH I can work to include the backup-- hang tight.

**Comment by timduly4** [comment]
@vlbBTH This fix should be implemented now-- give it a try.

**Comment by vlbBTH** [comment]
I have been able to install and execute `test_iri12_iri16.py` successfully!

Thank you a lot for your help @timduly4!

**Comment by timduly4** [comment]
@vlbBTH Great-- glad to hear it worked!
